import React, { ReactNode } from 'react';
import { Download, FileSpreadsheet, Printer } from 'lucide-react';
import DashboardLayout from '../../../components/dashboard/DashboardLayout';
import useAuthStore from '../../../store/useAuthStore';
import ReportSubNav from './ReportSubNav';
import { printReport } from './exportUtils';

interface ReportPageShellProps {
  title: string;
  description: string;
  icon: ReactNode;
  filters?: ReactNode;
  children: ReactNode;
  onExportCsv?: () => void;
}

const ReportPageShell: React.FC<ReportPageShellProps> = ({
  title,
  description,
  icon,
  filters,
  children,
  onExportCsv,
}) => {
  const user = useAuthStore((state) => state.user);
  const workspaceName = user?.workspace?.companyName || 'Seeakk';

  return (
    <DashboardLayout>
      <div className="flex-1 overflow-y-auto custom-scrollbar bg-gray-50 p-4 md:p-8 print:bg-white print:p-0">
        <div className="mx-auto max-w-[1400px] space-y-6">
          <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center print:hidden">
            <div>
              <h1 className="flex items-center gap-3 text-2xl font-black text-gray-900 md:text-3xl">
                {icon}
                {title}
              </h1>
              <p className="mt-1 text-sm text-gray-500">{description}</p>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={printReport}
                className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-bold text-gray-700 shadow-sm transition hover:bg-gray-50"
              >
                <Printer size={16} /> Print / PDF
              </button>
              {onExportCsv ? (
                <button
                  type="button"
                  onClick={onExportCsv}
                  className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-bold text-gray-700 shadow-sm transition hover:bg-gray-50"
                >
                  <FileSpreadsheet size={16} /> Export Excel
                </button>
              ) : null}
              <button
                type="button"
                onClick={printReport}
                className="flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-emerald-600"
              >
                <Download size={16} /> Download HTML Report
              </button>
            </div>
          </div>

          <ReportSubNav />

          {filters}

          <div className="hidden border-b-2 border-gray-900 pb-4 print:block">
            <div className="mb-2 flex items-center justify-between">
              <h1 className="text-3xl font-black text-gray-900">{workspaceName}</h1>
              <p className="text-sm font-bold text-gray-500">Page</p>
            </div>
            <h2 className="text-2xl font-black text-gray-900">{title}</h2>
            <p className="mt-2 font-bold text-gray-600">Generated on: {new Date().toLocaleString()}</p>
            <p className="text-sm text-gray-500">Generated by: {user?.name || user?.email || 'System'}</p>
          </div>

          {children}
        </div>
      </div>
    </DashboardLayout>
  );
};

export default ReportPageShell;
